### ISSUE TITLE
Why not to use semicolon by default in `avy-keys`?

### ISSUE THREAD

**Issue by mrkkrp** [abo-abo/avy#132]
Any reason? Semicolon is a normal key on home row — why not to use it? The more keys we have, the shorter combinations we need to type. I myself have switched to Dvorak: `'(?a ?o ?e ?u ?i ?d ?h ?t ?n ?s)` and only now noticed that you've got fewer keys by default with Avy.

**Comment by abo-abo** [comment]
> Semicolon is a normal key on home row — why not to use it?

Not on my keyboard, I use it as <kbd>Mod4</kbd>.

> The more keys we have, the shorter combinations we need to type

True, but the more keys we have, the more keys we have. So while each combination becomes shorter, each element of the combination has more variety and is thus harder. That's why I chose to have 9 keys by default for `avy`, instead of 72 keys like `ace-jump-mode` had.

Having 10 keys instead of nine wouldn't do too much, only move the 1-key threshold from 9 cands to 10, and the 2-key threshold from 81 cands to 100. If it's important for the user, it can be easily customized.

I'm not really opposed to the change, it's just the current setup was working fine for a while.  If there's popular demand to make the change, or some interesting research that proves that e.g. the average number of cands is close to 90 +/- 10, then it makes sense to increase `(length avy-keys)`.

**Comment by mrkkrp** [comment]
I don't think it will be a popular request :-) By the way the decision with placing all the keys on the home row is a win. Nice package, I even abused it for other things you probably haven't in mind when you wrote it: https://github.com/mrkkrp/ace-popup-menu.

I think there is no reason to keep this open.

**Comment by abo-abo** [comment]
> https://github.com/mrkkrp/ace-popup-menu

I'm using it right now, thanks. I've played around with using `avy` for Ispell corrections, but then found using `flyspell-correct-word-before-point` and `ace-popup-menu` better.

**Comment by mrkkrp** [comment]
Yeah, I personally like to be able to choose right collection explicitly, without guessing. Here is this menu thing in sepapate package BTW: https://github.com/mrkkrp/avy-menu. I want to make menu for fast insertion of Unicode symbols with it (menus will be user-defined and will do wrapping with paired characters like “” «» and a lot more) :-) That avy-powered selection should be nice interface for this.
