### ISSUE TITLE
Bad behavior with fill-column indicator turned on

### ISSUE THREAD

**Issue by shivamkalra** [abo-abo/avy#135]
Thanks for the wonderful plugin. I use it a lot, however there is minor issue in `avy-goto-line` with `fci-mode` turned on.

# Observed Behaviour

- Avy shows jump candidates around line drawn by `fci-mode` as shown in image below.

![2016-02-10-170145_792x578_scrot](https://cloud.githubusercontent.com/assets/1386352/12963465/bf0c191e-d018-11e5-9851-b8b4f678f48f.png)

# Reproduction Steps

- Set `fill-column` to 80 by interactively calling `set-fill-column`
- Enable `fci-mode`
- Call `avy-goto-jump`

**Comment by abo-abo** [comment]
Can be fixed in user config:

```elisp
(defadvice avy-goto-line (around avy-fci activate)
  (fci-mode -1)
  ad-do-it
  (fci-mode 1))
```

Otherwise, it's pretty hard. 

Actually, avy works correctly here: `fci-mode` puts a huge `:after-string` overlay on the previous line. This overlay shifts the beginning of line, and avy still shows the markers at the beginning of line. So maybe the bug could be fixed on `fci-mode` side: attach each margin to its own line, instead of the previous line.

**Comment by abo-abo** [comment]
Since there's nothing further that I can do here, I'm closing this one.
