### ISSUE TITLE
Copy, Cut and Delete everything between current and jumped position

### ISSUE THREAD

**Issue by rrittwikc** [abo-abo/avy#138]
First, thanks a lot for the plugin; I use it all the time.

I have some weird requests.

If someone wishes to jump from current position to a new position, she wants to do that for four possible reasons.

1. To do something in that new position.
2. Delete everything from current position to new position.
3. Copy everything from current position to new position.
4. Cut everything from current position to new position.

This plugin has currently made it possible to jump to the new position very efficiently, and so it is useful for 1 only.
So, I would like to request for the rest.

I know I can do the following -

1. Go to beginning of the line or word
2. C-SPC
3. Jump using this plugin
4. Delete, copy or cut

But what I am requesting will reduce at least two keystrokes per use.
Also, in case of copy it will not move the cursor.

So, I am requesting for six functions that I can bind to some keys.

1. Delete everything from current line to jumped line. (avy-line-delete)
2. Delete everything from current word to jumped word. (avy-word-delete)
3. Copy everything from current line to jumped line. (avy-line-copy)
4. Copy everything from current word to jumped word. (avy-word-copy)
5. Cut everything from current line to jumped line. (avy-line-cut)
6. Cut everything from current word to jumped word. (avy-word-cut)

For all the six it does not matter whether you include or exclude the jumped line or word.

I personally don't think that the equivalent char functions will be used regularly.
But at least I will use those above mentioned functions regularly.
Also I have seen code of similar type in the plugin, for example avy-copy-region.

My knowledge in elisp is almost zero, otherwise I could have sent you a pull request :).

**Comment by abo-abo** [comment]
You're requesting too much stuff, and all of the stuff also does too much. In my experience, it's much better to have simple functions that you can combine in straightforward ways, rather than tonnes of inflexible permutations.

Still, some of the stuff that you ask for can be added to `avy-dispatch-alist`. Here's how it works: if `avy-goto-word-or-subword-1` is <kbd>M-t</kbd>, and going to the word of interest is <kbd>M-t aj</kbd>.  Then <kbd>M-t amj</kbd> will mark the word, <kbd>M-t axj</kbd> will kill the word, <kbd>M-t anj</kbd> will copy the word.

The corresponding functions `avy-action-kill avy-action-mark avy-action-copy` are very straightforward. It would be pretty easy to add stuff that cuts and deletes from the current point to the selected point.  You can even add that stuff just for your own config.

**Comment by rrittwikc** [comment]
Thanks for the tips. I will look into avy-action-copy.

Once again thank you for this great plugin :).
