### ISSUE TITLE
New package `avy-flycheck`: `avy` interface for `flycheck` syntax errors navigation.

### ISSUE THREAD

**Issue by magicdirac** [abo-abo/avy#159]
Hi, I wrote a small package called [`avy-flycheck`](https://github.com/magicdirac/avy-flycheck).

https://github.com/magicdirac/avy-flycheck

It provides a simple [`avy`](https://github.com/abo-abo/avy) interface for navigation [`flycheck`](https://github.com/flycheck/flycheck) syntax errors.

Any Criticism or Suggestions are Welcome.

**Comment by abo-abo** [comment]
Thanks, although I don't know if I can be of much help since I don't use flycheck (I have an aversion to squiggly lines).

> Any Criticism or Suggestions are Welcome.

When using `window-end`, it's usually correct to always set the `update` argument.

Prefer `(require 'cl-lib)` to requiring `cl`. This means e.g. substituting `remove-if` with `cl-remove-if`.

That's it, the rest of the code looks fine to me.
