### ISSUE TITLE
[Question] Is there an option to navigate like this?

### ISSUE THREAD

**Issue by karambaq** [abo-abo/avy#242]
Hello, I'm ex-vimmer, in vim I used easymotion to jumping, and here the example what I mean:

Emacs avy:

<img width="1238" alt="2018-08-05 0 09 32" src="https://user-images.githubusercontent.com/14233969/43680467-f7c6b034-9843-11e8-8a49-2c64e530ef70.png">

Vim-easymotion:

<img width="1280" alt="2018-08-05 0 09 55" src="https://user-images.githubusercontent.com/14233969/43680469-fdd48f28-9843-11e8-9209-8a4550ee3ee5.png">

As you can see, in vim closest jumps to current position usually a one symbol reference, with avy it almost always to two symbols

**Comment by abo-abo** [comment]
Avy sorts paths in order that they appear in the buffer. This is both simple and consistent.

But I see how your suggestion could be a useful improvement. I even think it was suggested somewhere before.

It should not be too difficult to implement: just sort the `lst` argument to `avy-tree` in order of closeness to the point position. Maybe someone could make a PR? Otherwise, I'll implement this myself later.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by karambaq** [comment]
@abo-abo 
Perfect, thanks so much!

**Comment by lshoravi** [comment]
@abo-abo Is it possible to get this behavior for ´avy-goto-word´ as well? :)

**Comment by abo-abo** [comment]
@lshoravi You can customize it like this:

```elisp
(add-to-list 'avy-orders-alist '(avy-goto-word-1 . avy-order-closest))
```

**Comment by lshoravi** [comment]
Fantastic! Thank you :+1:
