### ISSUE TITLE
The link part of org-mode links is ignored.

### ISSUE THREAD

**Issue by whatacold** [abo-abo/avy#261]
Hi,

I noticed there is an issue that `avy-goto-char` will only match the description part of org link:
1. `git clone https://github.com/abo-abo/avy.git` and `cd avy`
2. `emacs -Q -l avy.el` to run a fresh emacs instance
3. Open a org-mode buffer and insert below two lines, then `M-x org-toggle-link-display` to display it literally.

       github
       [[https://github.com/abo-abo/swiper][abo-abo/swiper - github.com]]

4. `M-x avy-goto-char RET g` will only highlight the `g`s in the first line and second one of the second line,
i.e. the one in `https://github.com/abo-abo/swiper` is not ignored.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by duianto** [comment]
It seems to be working for `M-x avy-goto-char RET g` now:

#### Before

![before](https://user-images.githubusercontent.com/13420573/51397600-d7de3900-1b41-11e9-9a07-b19be881554a.png)

#### After

![after](https://user-images.githubusercontent.com/13420573/51397612-dca2ed00-1b41-11e9-8c0b-a783b49fc67a.png)

#### But the same issue remains for other `avy-goto-*` commands
A quick test showed that these commands still ignore the url part of the link:
```
avy-goto-subword-0
avy-goto-subword-1
avy-goto-symbol-1
avy-goto-symbol-1-above (with the cursor below the org link)
avy-goto-symbol-1-below (with the cursor above the link)
avy-goto-char-timer
```

I'm not sure how a symbol is defined, but if `avy-goto-symbol-1` targets the first character in a "group" of characters, then those commands probably work as expected since `github` inside the link part.

**Comment by whatacold** [comment]
It works fine for `avy-goto-char` now, but I can confirm that it remains at least for `avy-goto-char-timer`.

@duianto Thanks for helping test.

**Comment by abo-abo** [comment]
@duianto Thanks for testing, I've added fixes for the functions you mentioned. Could not reproduce `avy-goto-symbol-1-*` though, please add a repro scenario.

**Comment by duianto** [comment]
I followed the steps above:
- Start Emacs with Avy: `emacs -Q -l C:\Users\username\.emacs.d\elpa\26.1\avy-20190117.1647\avy.el`
(the path is to the Spacemacs install location, but I'm guessing that nothing Spacemacs related is loaded with `emacs -Q`)
- Open a new buffer named `test`: `C-x b` `test` `RET`
- Copy the two lines below and paste `C-y` them into the `test` buffer:
```
github
[[https://github.com/abo-abo/swiper][abo-abo/swiper - github.com]]
```
- Switch to org mode: `M-x` `org-mode` `RET`
- Toggle org mode link display: `M-x` `org-toggle-link-display` `RET`
- With the cursor at the end of the second line (or below it if a newline was came with the pasted lines):
`M-x` `avy-goto-symbol-1` `g`
or
`M-x` `avy-goto-symbol-1-above` `g`

Both cases show (the same as the "Before" screenshot above):

![](https://user-images.githubusercontent.com/13420573/51397600-d7de3900-1b41-11e9-9a07-b19be881554a.png)

without the `g` in the links word `github` having a target.

- With the cursor at the beginning of the first line:
`M-x` `avy-goto-symbol-1-below` `g`

Shows the same thing, a missing link `g` target, but the `a` and `s` targets are swapped (I'm guessing because the targets are set from the cursor outwards.

**Comment by duianto** [comment]
Just tested the latest version `avy-20190121.1644` and:
```elisp
avy-goto-subword-0
avy-goto-subword-1
avy-goto-char-timer
```
all work as expected, an avy goto target is added to the link as well. 👍

**Comment by abo-abo** [comment]
> In that case it's probably working as expected.

That's what I suspected. See the doc:

> Jump to the currently visible CHAR at a symbol start

In your example, "g" is not at a symbol start. So it works as expected. Thanks for testing.
